### ISSUE TITLE
Support for auto closing resource

### ISSUE THREAD

**Issue by MrTimeey** [s-frick/jcontrols#10]
Given is a classic try example with autoclosing resource:
```java
private ObjectMapper om = new ObjectMapper();

try (InputStream resource = DataLoader.class.getResourceAsStream("resource.json")) {
   String inputObject = IOUtils.toString(resource, StandardCharsets.UTF_8);
   return om.readValue(objString, CustomObject.class);
} catch (IOException e) {
   throw new RuntimeException(e);
}
```

It would be nice if Try can also autoclose resources:
```java
private ObjectMapper om = new ObjectMapper();

return Try
    .of(() -> DataLoader.class.getResourceAsStream("resource.json"))
    .map(res => {
           String inputObject = IOUtils.toString(resource, StandardCharsets.UTF_8);
           return om.readValue(objString, CustomObject.class);
    });
```

The resource should be closed at the end of the map method. 

Maybe it schould have a new Method like `Try.ofResource`?

**Comment by MrTimeey** [comment]
Additional question: 
Do I have to use an other Try for the `om.readValue` call because it can thrown an error? Is it possible to flatMap a Try or schould the call be safe because it's already in a mapping of a try?

**Comment by s-frick** [comment]
Thank you for the issue and feedback. As of v0.4.0 you can use Try with up to 5 resources. See an example [here](https://github.com/s-frick/jcontrols/blob/8407d13ca71ec073460f097fb502345e630b8919/src/test/java/io/github/sfrick/jcontrols/TryExampleTest.java#L27).

Regarding your 2nd question. Yes you should wrap `om.readValue` in a Try if it throws otherwise this case is unhandled. You can use `flatmap` instead of `map` to get rid of the Try<Try<?>> construct.
